### ISSUE TITLE
Styles not applied to rungeon.html when using npm

### ISSUE THREAD

**Issue by Shabbyconnor** [devkennyy/rungeon#134]
When testing code using a localhost server (```npm start```) no styling is applied and an error is thrown.

<img width="1440" alt="Screen Shot 2022-07-24 at 11 39 06 PM" src="https://user-images.githubusercontent.com/109128466/180705779-d2eb02bd-33fe-4f11-9d6c-f35f8f80c108.png">

<img width="468" alt="Screen Shot 2022-07-24 at 11 35 06 PM" src="https://user-images.githubusercontent.com/109128466/180705870-06a1ab93-74e6-476d-b575-4522aec1dd36.png">

**Comment by Shabbyconnor** [comment]
This could very well be on my end. Just wanted to see if anyone else had this issue.

**Comment by devkennyy** [comment]
```js
rungeon.use(express.static(__dirname + '/public'));
```
Since the configuration is `/public`, file references must begin with a `/`. I can already make note of some links missing the `/`. 
Would you like to try a fix?

**Comment by Shabbyconnor** [comment]
Changing the file references doesn't seem to work. 😕

**Comment by devkennyy** [comment]
Hmm, this is odd. I do get this error as well. Themes are getting a rework so I guess we'll just have to wait.

**Comment by GruelingPine185** [comment]
@Shabbyconnor This issue is caused because as devkennyy said, we are redesigning the theme system and `public/rungeon.html` (shown below) still has a link to a CSS file that existed with the old theme system.

https://github.com/devkennyy/rungeon/blob/a629f430c546c6777a13884e0ff1ffc4c48dbb6a/public/rungeon.html#L6-L13

To clarify the difference between the two:

## Old Theme System

- Had CSS files per theme (`public/styles/default.css`, `public/styles/rgb.css`, etc.)
- Used JS to manipulate the CSS theme path (doing so changes the theme)

## New Theme System

- Only 1 CSS file with several classes (`public/styles/themes.css`)
- Uses JS to change a single class attribute on `<body>` (doing so changes the theme)

**Comment by GruelingPine185** [comment]
@devkennyy @Shabbyconnor I have a solution now. It's on the `stage-remake` branch. The only issue I have now is that I can't get index.html to accept the incoming theme from localStorage. If index.html is hardcoded to theme-default, that is the only theme that gets rendered on that page. Without the theme being hard-coded to index.html, this happends:

<img width="727" alt="Screen Shot 2022-07-25 at 1 26 26 PM" src="https://user-images.githubusercontent.com/66073333/180838047-23416db6-25c4-453f-9443-b32e905289cd.png">

**Comment by devkennyy** [comment]
You can merge it into main if you like, it won't affect `rungeon.live`. The only thing stopping me from deploying is the themes not working.
