### ISSUE TITLE
Stage four does not work on mobile

### ISSUE THREAD

**Issue by devkennyy** [devkennyy/rungeon#34]
You cannot drag the key to the lock, I'd have to read up on the api

**Comment by Andreu-G** [comment]
Could instead create kind of an "inventory", and make the key appear in the inventory when the user clicks on it. That way we don't have to deal with drag and drop.

**Comment by devkennyy** [comment]
We could but I want to create some uniqueness in the levels. An inventory would unlock alot more creativity however. There is alot of room to work with on the page and the more content we have, the more we can hide things in.

**Comment by Andreu-G** [comment]
If you want to add creativity to it, but also add an inventory system, you could lower the opacity of the key and instead set its position behind some word so that the user has to find it and click on it.

I'm not sure how difficult setting up a drag and drop would be (windows-style I mean), so really depends on what you want to do with the stage itself.
