### ISSUE TITLE
fix passionfruit typo

### ISSUE THREAD

**Issue by devkennyy** [devkennyy/rungeon#65]
main.js > line 129

**Comment by Aspireve** [comment]
Hey @devkennyy  could I do this?

**Comment by samvanderlinden** [comment]
Is the issue that it should be `document.getElementById("passionfruit").innerHTML = "passionfruit";` instead of `document.getElementById("passionfruit").innerHTML = "passionfruit  ";`? If so, I also see typos for the below elements.

`document.getElementById("serika").innerHTML = "serika  ";
  document.getElementById("cobalt").innerHTML = "cobalt  ";
  document.getElementById("hedge").innerHTML = "hedge  ";
  document.getElementById("passionfruit").innerHTML = "passionfruit  ";
  document.getElementById("rgb").innerHTML = "rgb  ";
  document.getElementById("dots").innerHTML = "dots  ";`

**Comment by devkennyy** [comment]
Sorry no, the typo is that passionfruit is literally misspelled. If you search for 'passionfriut', you'll see. The space after the theme name is to ensure the tick looks nice when it is added. Although, we should probably be doing it like so:
"cobalt" += " ✔️"

**Comment by samvanderlinden** [comment]
It looks like this was already fixed with this PR https://github.com/devkennyy/rungeon/pull/62

**Comment by devkennyy** [comment]
I'll create a new issue regarding the spacing change.
