### ISSUE TITLE
Replace return and continue with left and right icons

### ISSUE THREAD

**Issue by devkennyy** [devkennyy/rungeon#8]

**Comment by lodenrogue** [comment]
Is this kind of what you're looking for?
![Screenshot from 2022-07-06 22-30-21](https://user-images.githubusercontent.com/2889651/177677884-069e62de-8561-4d4b-bc42-509b155c6b32.png)

**Comment by devkennyy** [comment]
I think we should replace the buttons completely. Otherwise the back button is misleading since it returns you to the front page. 
Maybe the return button should be placed elsewhere? Or not exist at all...I'd love to hear your thoughts?

**Comment by Andreu-G** [comment]
> I think we should replace the buttons completely.

Since the project uses a fontawesome kit, how about instead of using emojis, add the round arrow icon? I believe it would give it a more clean look. I'm specifically talking about this one: https://fontawesome.com/icons/circle-arrow-right?s=solid

> Maybe the return button should be placed elsewhere?

I agree with you, it's currently very misleading, as you'd expect to be able to go back to the previous stage.
IMO, either we put the button somewhere else with a red color to identify it better, or we change its behavior to go back to the last stage.

**Comment by Andreu-G** [comment]
Yeah, I agree with you. Honestly, I think refactoring everything would be the most ideal thing right now, even more since the project is in its early stage and it shouldn't be too difficult.

There are also some inconsistencies that can be fixed pretty easily and would make the code much more readable.

For example, there's both an ID and a class for each stage; it doesn't really have any benefit. Remember that one element can only have one ID, but can have as many different classes as you want.

Since stages keep the same design (for now), I think it would be best to create a global css class called "stage" which has all the common info for stages (background color, button positions etc), and then give each stage their own ID in case we want to make, for example, a stage have the background as dark red instead.

All in all, refactoring the button to go back to the previous stage would probably end up being a problem in the future after refactoring everything, and would most likely be re-done anyway, so I think it'd be best to deal with the stage system first.

I'd love to try and get a new system going. I should be free this weekend to try some designs. I'll make a pull request when it's done 🙂

**Comment by devkennyy** [comment]
> I'd love to try and get a new system going. I should be free this weekend to try some designs. I'll make a pull request when it's done 🙂

Thank you!
